# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
podfile: Example/Podfile
osx_image: xcode7.1
xcode_workspace: Example/ThreeLevelAccordian.xcworkspace
xcode_scheme: ThreeLevelAccordian-Example
xcode_sdk: iphonesimulator9.3
